---

- name: Deploy
  hosts:
  - tag_Name_reducto-frontend-01
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      - name: Copy project jar
        copy: src=../target/scala-2.10/nlp-akka_2.10-0.1.jar dest=/usr/lib/akka/deploy

      - name: Run Akka
        command: /usr/lib/akka/bin/akka com.winston.api.ApiBoot
