---

- name: Kill-Dist
  hosts:
  - tag_Name_reducto-frontend-01
  - tag_Name_reducto-worker-01
  - tag_Name_reducto-supervisor-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous run
        command: killall java
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/


- name: Re-deploy Frontend
  hosts:
  - tag_Name_reducto-frontend-01
  
  user: ubuntu
  sudo: true
  gather_facts: false

  tasks:
    - name: Run Frontend
      command: nohup /usr/local/reducto-dist/bin/start com.winston.api.ApiBoot &
      async: 450000
      poll: 0


- name: Re-deploy Worker
  hosts:
  - tag_Name_reducto-worker-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Run worker 1
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 2
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 3
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 4
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 5
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 6
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 7
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

      - name: Run worker 8
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.WorkerDaemon &
        async: 450000
        poll: 0  

- name: Re-deploy Supervisor
  hosts:
  - tag_Name_reducto-supervisor-01
  
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Run supervisor 1
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.Supervisor &
        async: 450000
        poll: 0  
