---

- name: Re-deploy
  hosts:
  - tag_Name_reducto-frontend-01
  - tag_Name_reducto-backend-01
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      - name: Kill previous run
        command: killall java
        
      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Frontend Akka
        command: nohup /usr/local/reducto-dist/bin/start com.winston.api.ApiBoot &
