---

- name: Deploy Supervisor
  hosts:
  - tag_Name_reducto-supervisor-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      
      - name: Kill previous run
        command: killall java
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Supervisor Akka
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.SupervisorDaemon &
        async: 450000
        poll: 0